export enum ActionType {
  SEARCH_COUNTRIES = 'SEARCH_COUNTRIES',
  FETCH_COUNTRY = 'FETCH_COUNTRY',
  //fetch countries
  FETCH_COUNTRIES = 'FETCH_COUNTRIES',
  FETCH_COUNTRIES_ERROR = 'FETCH_COUNTRIES_ERROR',
  FETCH_COUNTRIES_SUCCESS = 'FETCH_COUNTRIES_SUCCESS',
}
