export enum ActionType {
  //search countries
  SEARCH_COUNTRIES = 'SEARCH_COUNTRIES',
  SEARCH_COUNTRIES_SUCCESS = 'SEARCH_COUNTRIES_SUCCESS',
  SEARCH_COUNTRIES_ERROR = 'SEARCH_COUNTRIES_ERROR',
  //fetch countries
  FETCH_COUNTRIES = 'FETCH_COUNTRIES',
  FETCH_COUNTRIES_ERROR = 'FETCH_COUNTRIES_ERROR',
  FETCH_COUNTRIES_SUCCESS = 'FETCH_COUNTRIES_SUCCESS',
  //filter countries
  FILTER_COUNTRIES = 'FILTER_COUNTRIES',
  FILTER_COUNTRIES_SUCCESS = 'FILTER_COUNTRIES_SUCCESS',
  FILTER_COUNTRIES_ERROR = 'FILTER_COUNTRIES_ERROR',
  //fetch country
  FETCH_COUNTRY = 'FETCH_COUNTRY',
  FETCH_COUNTRY_SUCCESS = 'FETCH_COUNTRY_SUCCESS',
  FETCH_COUNTRY_ERROR = 'FETCH_COUNTRY_ERROR',
  //current country name
  CURRENT_COUNTRY_CODE = 'CURRENT_COUNTRY_CODE',
  //current mode: light mode / dark mode
  CHANGE_CURRENT_MODE = 'CHANGE_CURRENT_MODE',
}
